Q1 = "SELECT * FROM Movie ORDER BY rank DESC LIMIT 10;"
Q2 = "SELECT * FROM Movie ORDER BY rank DESC LIMIT 10 OFFSET 10;"
Q3 = 'SELECT name FROM Movie WHERE year > 2004;'
Q4 = "SELECT name FROM Movie WHERE rank < 1.1;"
Q5 = "SELECT * FROM Movie WHERE year IN (2004, 2005, 2006);"
Q6 = "SELECT name, year FROM  MOVIE WHERE name LIKE 'Harry%';"
Q7 = "SELECT * FROM Actor WHERE fname LIKE 'Christin' AND NOT lname LIKE 'Watson';"
Q8 = "SELECT * FROM Actor WHERE fname LIKE 'Woody' AND lname LIKE 'Watson';"
Q9 = "SELECT name FROM Movie WHERE year = 1990 AND rank = 5;"
Q10 = "SELECT * FROM Actor WHERE fname LIKE 'Christin' AND lname LIKE 'Watson';"
Q11 = "SELECT name FROM Movie WHERE year BETWEEN 2003 AND 2005;"
Q12 = "SELECT DISTINCT year FROM Movie ORDER BY year ASC;" 
Q13 = "SELECT * FROM Actor WHERE (fname LIKE 'Christin' OR lname LIKE 'Watson') AND gender ='M' ORDER BY fname ASC LIMIT 10;"